config/routes.rb
Neosoft329::Application.routes.draw do

  resources :questions, :only => [:index]  do
    collection do
      post 'print_que_ans'
    end  
  end  
  root :to => "home#index"
  
  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/question.rb
class Question < ActiveRecord::Base	

  has_many :question_answers

  scope :selected, lambda{ |ids| includes(:question_answers).where('id IN  (?)', ids) }
  
  attr_accessible :image, :info, :level, :status
  mount_uploader :image, AvatarUploader	  

end

app/models/question_answer.rb
class QuestionAnswer < ActiveRecord::Base	

  belongs_to :question

  attr_accessible :ans, :image, :is_correct
  mount_uploader :image, AvatarUploader	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
  	@questions = Question.paginate(:page => params[:page], :per_page => 5)
  end	

  def print_que_ans
  	if !params[:question_all].nil?  		
  	  @questions = Question.includes(:question_answers)
    elsif !params[:question_ids].nil?      
      @questions = Question.selected(params[:question_ids])      
    else       
    end		
    respond_to do |format|
      format.js
    end  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/index.html.erb
<h1 class="align">Welcome</h1>
<%= link_to "Questions", questions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Neosoft329</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <%= yield %>
</div>
</body>
</html>

app/views/questions/_question.html.erb
  <tr>
    <td>
  	  <%= question.info %>
    </td>	
 
    <td>
      <%= question.status %>
    </td>

    <td>
  	  <%= question.level %>
    </td>

    <td>
      <%= image_tag question.image %>
    </td>
    <% if index %>
      <td>
        <%= check_box_tag "question_ids[]", question.id %>
      </td> 
    <% else %>  
      <table>
        <th>
          Answer
        </th> 
 
        <th>
          Correct?
        </th>

        <th>
          Image
        </th>
        <%= render(:partial => 'question_answer', :collection => question.question_answers)  || 'There is no answers to be displayed.' %>
      </table>
    <% end %>
  </tr>  
  

app/views/questions/_question_answer.html.erb
<tr>
  <td>
  	<%= question_answer.ans %>
  </td>	
 
  <td>
    <%= question_answer.is_correct %>
  </td>

  <td>
    <%= image_tag question_answer.image %>
  </td>
</tr>

app/views/questions/index.html.erb
<%= link_to 'Home', root_path %>
<%= form_for :question, :url => print_que_ans_questions_path, :remote => true do %>

  <table>
    <th>
      Question
    </th>

    <th>
      Status
    </th>

    <th>
      Level
    </th>

    <th>
      Image	
    </th>

    <th>
      <%= check_box_tag :question_all %>
    </th>
    <%= render(:partial => "question", :collection => @questions, :locals => { :index => true }) || "There's no questions to be displayed." %>
    <tr>
      <td>
  	    <%= submit_tag 'Submit' %>
      </td>
      <td>        
        <input type="reset" value="Reset">
      </td>      
    </tr>
<% end %>

</table>

<%= will_paginate @questions %>

app/views/questions/print_que_ans.js.erb
printPopup=window.open('','print popup', "scrollbars=1, height=500, width=450");
var temp = printPopup.document;
temp.write("<html><head><title>Neosoft329 print question answer</title>");
temp.write("<link rel='stylesheet' href='/assets/home.css'>");
temp.write("</head><body><div id='container'><%= escape_javascript(render(:partial => 'question', :collection => @questions, :locals => { :index => false }) || 'There is no questions to be displayed.') %> <%= escape_javascript(render :partial => 'shared/print_close') %>");
temp.write('</div></body></html>');
temp.close();

app/views/shared/_print_close.html.erb
<div>
  <%= button_to_function 'Close', 'javascript:self.close()' %>
  <%= button_to_function 'Print', 'javascript:self.print()' %>
</div>